### ISSUE TITLE
Possible structures and likely structures fields do not correctly update on larger structures

### ISSUE THREAD

**Issue by Pshepp** [GLYCAM-Web/website#108]
**Tool:**
https://test.glycam.org/cb/options_b

**Bug Description:**
Sometimes ith larger structures both the `possible structures` field and the `likely structures` field only and always report `>2^32`

**To Reproduce:**
Go ahead and build a structure that is very large so you get to the `options_b` page. An example structure has been sent to Dan.

1. go to https://test.glycam.org/txt/
2. Enter the large sequence and then submit and problem should be apparent 

**Expected behavior**
both the `possible structures` field and the `likely structures` field accurately show values

**Screenshots**
Sorry for this being a small screenshot, I don't want to make the sequence used super public

![image](https://user-images.githubusercontent.com/17117182/202843429-75f0008a-5b09-4232-836d-2120156da8c4.png)

**Device & OS Details**
Linux Desktop, Brave Browser 107.1.45.127

**Additional context**
Feel free to DM me on slack if I need to add more to this ticket

**Comment by Lachele** [comment]
The numbers of possible and likely structures do not change.  Only the number of chosen/selected structures can change.  We could certainly display a proper number.  Back when, we decided that if there were more than 32 flexible linkages, that there was little point taking time calculating the exact numbers.  At that time, the website code was doing the checking/counting, typically client-side.  Rather than walk the sequence each time and count the number of 2's and 3's to multiply together, we decided to just say there were "too many".  Once the user dropped the number of flexible linkages below 32, we would do the actual calculation.  We left it in terms of "2^32" as a clue to the user that they needed to drop the number of flexible linkages down.  But, it's not that hard to do the calculation now.  If we don't do the calculation, would you prefer a base-10 representation, such as ">4 billion" or ">4e9"?  If we do the calculation, would you want all N digits in this arbitrarily-sized integer or should we be cute and say "more than Avogadro's number" and such?

**Comment by gitoliver** [comment]
The behavior is good. I can change the text if you want give example of what way you want to say greater than 2^32

**Comment by Pshepp** [comment]
Okay, I see. I almost Dm'd Oliver about this to check if it was expected but didn't lol, sorry about that. The output just worried me that maybe some of the big GMML changes might have passed something different than usual.

If you guys think that having something similar to `greater than 4.29e9` (or some specific amount of sig-figs) would be better, then I am game. This would take up more space tho, which could cause extra headaches for our front-end people when it comes to elegantly changing the page depending on window resolution. Since this is expected behavior I will leave it up to yall to make a decision about what to do, but I think we can consider this an extremely low priority ticket.

**Comment by gitoliver** [comment]
Let's leave it as is for now. If a user or Rob asks about it we will rule it unintuitive and ask for input on what it could be.
