### ISSUE TITLE
Carbohydrate sequence cannot be more than 210 characters

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#116]
**Tool:**
Build via text. glycam.org/txt. Might be a limit in other tools too.

**Bug Description:**
If you enter a sequence that is too long, you get a "invalid payload error". Too long is between 205 and 210 characters. Limit should be more realistically 2000 characters.

**To Reproduce:**
Enter DGlcpb1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me]b1-4DGlcpa1-OH

Note that the slightly shorter version works fine:
DGlcpb1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me]b1-OH

Also note:
If you enter something that is "too long" but contains a space e.g..
this contains a space DGlcpb1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me,6 Hi My Name is Frank the Octupus. Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me]b1-4DGlcpa1-OH

you get:
There was a problem making the default sequence request: Error: sequence contains a space:>>>this contains a space DGlcpb1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me,6 Hi My Name is Frank the Octupus. Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me]b1-4DGlcpa1-OH<<<
Which means that the request is going down to the gmml level. 

So first thing to figure out: Where is the "Invalid payload" error originating from?

**Comment by danwentworthart** [comment]
Was able to replicate in my devEnv.

The error originates in GEMS, as the response contains the message, and the reporting entity is "CommonServicer":


2023-02-02 07:50:44 AM - json_api.json_api - DEBUG - response['notices'][{'noticeType': ['error'], 'noticeCode': ['400'], 'noticeBrief': 'InvalidInputPayload', 'noticeMessage': ['An invalid payload was detected.'], 'noticeScope': 'Transaction', 'messagingEntity': 'CommonServicer', 'additionalInfo': None}]

I can dig through gems logs next.

**Comment by danwentworthart** [comment]
This issue occurs in GEMS, but maybe GMML is involved. I suspect that an exponential notation is being returned from GMML where GEMS anticipates an integer:

```
File "/programs/gems/gemsModules/deprecated/sequence/evaluate.py", line 42, in getLinkageOptionsFromGmmlcbBuilder
    gemsLinkageGeometryOptions.totalPossibleRotamers = int(cbBuilder.GetNumberOfShapes())

```

**Comment by gitoliver** [comment]
Ok the size of the string isn't the issue. It's the number of rotamers. In this Jan 15 2023 gems-test commit: [77d7fd65b62d494fb6422c486261dacbe1f3fab2](https://github.com/GLYCAM-Web/gems/commit/77d7fd65b62d494fb6422c486261dacbe1f3fab2) we are now converting the returned string to an int. The reason it's a string from gmml is that if the number of rotamers is >2^32 it returns that string instead of the number. So converting it to an int won't work when the number is too high.

**Comment by danwentworthart** [comment]
We believe this issue has been resolved. Submitting the problematic sequence via Build Via Txt is now possible. I was able to request a single conformer (all the checkboxes in the right-most col were checked, and no others), from the Options page, and that did reach the downloads page. I did not see the molecule load into the Options page litemol, but it did load into the downloads page.

However, I believe this other issue is related, regarding the number of build options being returned, and that issue is not yet resolved: https://github.com/GLYCAM-Web/gmml/issues/146

**Comment by Pshepp** [comment]
CURRENT WORKING ACTUAL SITE SETUP TAGS:
- `dev-env` = `yearning-yael`
- `GEMS` = `wistful-walker`
- `GMML` = `wistful-walker`

I wasn't clear in slack; apologies. This issue continues to affect our `*-test` stack, so we must fix it, but the problem does not affect our currently working actual site which displays the `>2^32` correctly. The message in slack was more to assist in helping track down where the bad changes were (ty Olli finding bad commit). 

For now, a valid and working temporary patch is replacing lines 42 - 45 in `evaluate.py` (https://github.com/GLYCAM-Web/gems/blob/gems-test/gemsModules/deprecated/sequence/evaluate.py#L42-L45) with the following:

```python
    ##################################################
    #booger patch by p - 2/2/2023
    try:
        gemsLinkageGeometryOptions.totalPossibleRotamers = int(cbBuilder.GetNumberOfShapes())
    except ValueError:
        gemsLinkageGeometryOptions.totalPossibleRotamers = 999
        
    likelyOnly = True
    
    try:
        gemsLinkageGeometryOptions.totalLikelyRotamers = int(cbBuilder.GetNumberOfShapes(likelyOnly))
    except ValueError:
        gemsLinkageGeometryOptions.totalLikelyRotamers = 999
    
    #end booger patch
    ##################################################
```

A couple of things to note:
- if we just remove the `int()` casting of the values, the site kinda works, but litemol sometimes acts up. Also, we don't know if L requires this to be an int anywhere else and the worms get mad at it
- if the values go over some amount, somewhere around 9000-ish, then litemol can also act up sometimes. Could be a red herring, but keeping the replacement value for `>2^32` at a lower number reduced bad behavior. I tried doing a hashed string for the replacement value, but the decimal representation of the hashed string is pretty large and would cause wonky litemol behavior
- also, for some reason, if we set the value to `1` or some small number litemol acts up
- it is probably good to force this to be an integer, fewer worries about having to deal with parsing a string and whatnot which will be nice for the future because it will help keep us in check. We _could_ pass the actual numerical value from `GMML` to `GEMS` instead of passing `>2^32` and then just handle displaying the string stuff in javascript; this way when we get the ability to handle even larger numbers of structures it will be a simple JS change to get what we would want to display instead of having to deal with GMML and whatnot (plus who knows, maybe we will want the actual number in the future i dunno)
- always remember to be careful about casting and to use it as a last resort, not in a bad way just make sure that if casting is used there is no "proper" method other than casting
- i don't like litemol

:japanese_ogre:

**Comment by gitoliver** [comment]
Yes multiple issues are layered here so it's confusing. To clarify: https://github.com/GLYCAM-Web/gmml/issues/146 is not related to this, it just triggered us finding a bug. Any sequence with >2^32 will trigger the bug introduced in gems-test [77d7fd65b62d494fb6422c486261dacbe1f3fab2](https://github.com/GLYCAM-Web/gems/commit/77d7fd65b62d494fb6422c486261dacbe1f3fab2). Ignore the gmml issue in relation to this, except that when testing for this in future once the gmml issue is resolved, we will need to pick a different sequence to test. 

LiteMol acting up may be unrelated. If it looks for a default structure and it isn't built yet, it can fail. So there is a race condition that might hurt finding other issues, if there are any.

I can make gmml pass up an int, but we need a way to tell the user when they go beyond int limits. Let's wait for L to return before deciding anything. For now actual is ok.

**Comment by Pshepp** [comment]
kk sounds good, gonna rely on yall to remember this lol

**Comment by danwentworthart** [comment]
There are elements at play here that aren't the fault of LiteMol. Better to say we are still working on how to load files quickly into LiteMol in a graceful way that works both in cases where the file already exists, and also in cases where it needs to wait. Dan's fault, not LiteMol.

**Comment by Lachele** [comment]
There is another issue here that isn't LiteMol.  

I removed the int cast and told Pydantic to accept either int or str as input in the relevant places.  So, '>2^32' is now acceptable as a value.  I will push these changes if they pass a little more testing.

But... this sequence should not be returning '<2^32'.  There just aren't that many rotamers.  See image.

To be sure, I'm using this sequence from the original 'to repro':  DGlcpb1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me]b1-4DGlcpa1-OH

![image](https://user-images.githubusercontent.com/8740751/220528098-1eb7c2c0-170a-4bff-bcb9-7de1a7904e7e.png)

**Comment by Lachele** [comment]
And... when I requested all 64 (from that same window), I only got 8.  I checked the build directories.  Only 8 were built, so the website is showing all that were made.

**Comment by Lachele** [comment]
Fixing that required re-fixing the single-conformer builds (without the int cast).  

I didn't write a test for the '>2^32' thing.  Please see the post above with the image.  A sequence that returns the string '>2^32' should have at least 32 bonds with 2 or more rotamers.

**Comment by gitoliver** [comment]
Incorrect number of rotamers calculated fixed on *-test branches
![image](https://github.com/GLYCAM-Web/website/assets/17079588/30749090-bf28-4e1c-bb66-f04cee618cdc)

**Comment by gitoliver** [comment]
[6DGlcpa1-6DGlcpa1-]<20>-OH It's also able to handle when it hits the limit (on *-test branches)
![image](https://github.com/GLYCAM-Web/website/assets/17079588/1592146d-6537-409f-86e6-7bf00f471519)
The bugs of counting rotamers and freaking out when a string is passed up instead of an int are fixed.
