### ISSUE TITLE
Why does my dev env not have a similar path to the website for downloads from the carb builder?

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#122]
Carb builder on website has a download path like this when building something without rotamers:
somethingSomething /sequence/cb/Builds/ae52aa82-3e61-4b17-ae2f-5bc06bdb0689/New_Builds/structure/
In my dev env it looks like this:
somethingSomething /sequence/cb/Builds/ae52aa82-3e61-4b17-ae2f-5bc06bdb0689/New_Builds$ ls
info.json  logs  structure.off  structure.pdb

Why is it different?

**Comment by danwentworthart** [comment]
For a second, I believe it was edited to have no conformer id for the default structure. For consistency, the word "structure" was settled on to be the "conformer id" for the default, so that urls and paths can always have one. I predict this difference you see has to do with transitioning, meaning something still needs updating in gems. Not being the one who edits this, I could be wrong, but I bet I'm close.

**Comment by Lachele** [comment]
Carb builder on website is correct. 

In your DevEnv, rm -rf the Builds and Sequences directories.  (unless you need to save something there, then just rename them).  When you build single-structure sequences again it should be correct.

This is the bug that I fixed by casting the number of rotamers to int.  I forgot about the 2^32 thing.  Both should work now (sequences with a single rotamer and with >2^32 rotamers).
