### ISSUE TITLE
Selenium Configuration Issue

### ISSUE THREAD

**Issue by HemanthReddy45** [GLYCAM-Web/website#144]
**Tool:**
Selenium Tests

**Bug Description:**
selenium module isn't found when we try to start the container. May be the configuration requires a revisit.

**To Reproduce:**
Run the dockerized selenium tests.
in "GLYCAM_Dev_Env/V_2/Selenium/bin" run the start.sh script.

Error Description :
"raceback (most recent call last):
  File "/home/labuser/Desktop/Dev_Env/GLYCAM_Dev_Env/V_2/Selenium/main.py", line 16, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'"

**Comment by danwentworthart** [comment]
I wonder if we need these scripts to be included in the mounted volumes? My current hypothesis is that maybe these are running outside the container. The container is built from an existing Selenium image. The container very likely does have selenium installed.

**Comment by Pshepp** [comment]
i am pretty sure that the selenium code does not run the code in the containers themselves but it has been a little since i looked at the code. This is something that would need to be fixed, cause as dan said i am fairly ceratin the python selenium module is in the pulled docker images so u gotta make sure ur running the selenium code within the images themselves

**Comment by cexum** [comment]
Selenium testing has been containerized.
