### ISSUE TITLE
Make Logging In Nicer

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#199]
**Is your feature request related to a problem? Please describe.**
https://jam.dev/c/500a7a56-39ee-44da-8807-60eeb42a45a2

When logging in if I give the wrong password it does a weird page jump, clears everything and tells me nothing. I.e. not even wrong password. If I give the correct password it does the same page jump and puts me on the same screen. So I think I'm not signed in as it's asking for my log in details again. Better to go somewhere else like the project page on successful log in.

**Comment by danwentworthart** [comment]
1. Added error msg hints to login form.
Commit #ce7e09ef8582b696f5bd88c011ed3259c9508d33
2. Redirect after successful login. Checking for no existence of redirect url, or empty string, and replacing both with home.
Commit #20582f7a136321adce37999bdc22653e7bc00c7a
3. "flash of unstyled content" (FOUC). This happens when the HTML content is rendered before the CSS is fully loaded. This could require a bit more than one approach, but I tried the first thing that came to mind, and it improved in my tests:
	 
	 Tried inheriting from base_glycam.html instead of glycam.html. May have addressed the issue. Please make a new ticket if this continues?

Commit #52e7a124b879b5eedf88bd9523cc8dabad0a7d5e
