### ISSUE TITLE
understated-ujevic deployment

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/website#81]
# understated-ujevic is deployed at test.glycam.org

## Please leave comments.

**Comment by gitoliver** [comment]
The first time I pick a structure from the oligosaccharide library, the default structure doesn't show up on the options page:
![image](https://user-images.githubusercontent.com/17079588/165556990-6bd5078b-8aaa-4d4e-8239-d301a6bdd632.png)
Reloading the page triggers it to show up. Pressing back, hitting reload (cause the spinning while is still happening otherwise) and then clicking again will sometimes show a structure, sometimes not. Might be related to how long it takes for the request to come back.
Can someone else confirm?

**Comment by Lachele** [comment]
Yeah, this sort of thing happens, particularly for larger structures.  Behind the scenes, GEMS is building a bunch of structures at the start (like 9 or so rather than one default), at the same time that options get sent back.  I'm pretty sure this is the underlying cause of the issue.  We never saw this before because the response was taking so long.  I'm waiting to learn what Dan has to say about the website's perspective before making a lot of decisions.  This happens in my DevEnv, not just online.  But, I wanted to get the speed-up pushed so we could start whacking on all the stuff that uncovered, like this.

**Comment by danwentworthart** [comment]
I am bug hunting today. I will aim at this and the error handling issues
first.
